//created on: May 5, 2020
package cepTrainingMonitor

//list any import classes here.
import tableTennisInstructor.model.drools.events.*;
import tableTennisInstructor.model.drools.facts.training.*;
import java.util.ArrayList;
import java.lang.Long;


//declare any global variables here


rule "Create badRacketSpeedEvent when training lvl iz BEGINER and racketSpeed is wrong "

    when
    	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.BEGINNER)
    	$lastShot: List(size >= 1) from
        	accumulate($t: 
        				SkillExecutionEvent(trainingExecutionId == $tre.id, 
        									(deltaSpeed >= 5.0 || deltaSpeed <= -5.0 ) &&
        									badRacketSpeedProcessed == false
        									)
        			   over window:time(2s)
        			  ,collectList($t))
    then
        for(Object $o: $lastShot) {
        	 SkillExecutionEvent $o1 = (SkillExecutionEvent) $o;
        	 $o1.setBadRacketSpeedProcessed(true);
        	 BadRacketSpeedEvent badRaketEvent = new BadRacketSpeedEvent();
        	 badRaketEvent.setSpeed($o1.deltaSpeed);
    		 update($o);
        	 insert(badRaketEvent);
        	 System.out.println("Kreiran event losa brzina reketa za pocetnicki nivo");
        }
end
