//created on: May 4, 2020
package cepTrainingMonitor

//list any import classes here.
import tableTennisInstructor.model.drools.events.*;
import tableTennisInstructor.model.drools.facts.training.*;
import java.util.ArrayList;
import java.util.List;
//list any import classes here.



//declare any global variables here

rule "Create Skill Correction Event when toMuchSuccessiveMissEvent is present"
	salience 90
    when
    	$tre: TrainingExecution()
        $t: List(size == 1) from
        			 accumulate( 
        					$ta: ToMuchSuccessiveMiss(processed == false) over window:length(1),
        					collectList($ta)
        			) 
    then
    	insert(new SkillCorrectionEvent());
    	ToMuchSuccessiveMiss $t1 = (ToMuchSuccessiveMiss) $t.get(0);
    	$t1.setProcessed(true);
		update($t1);
		System.out.println("potrebna korekcija jer ima previse uzastopnih promasaja");
end

rule "Create Skill Correction Event when toMuchSuccessiveMissEvent and BadBodyPositionEvent are present"
	salience 100
    when
    	$tre: TrainingExecution()
        $t: List(size == 1) from
        			 accumulate( 
        					$ta: ToMuchSuccessiveMiss(processed == false) over window:length(1),
        					collectList($ta)
        			)
        $bbE: List(size == 1) from
        			 accumulate( 
        					$ta: BadBodyPositionEvent(processed == false) over window:time(6s),
        					collectList($ta)
        			) 
    then
    	insert(new SkillCorrectionEvent());
    	ToMuchSuccessiveMiss $t1 = (ToMuchSuccessiveMiss) $t.get(0);
    	$t1.setProcessed(true);
		update($t1);
		
		BadBodyPositionEvent $bbE1 = (BadBodyPositionEvent) $bbE.get(0);
    	$bbE1.setProcessed(true);
		update($bbE1);
		
		System.out.println("potrebna korekcija jer ima previse uzastopnih promasaja i los je polozaj tela");
end


