//created on: May 4, 2020
package cepTrainingMonitor

//list any import classes here.
import tableTennisInstructor.model.drools.events.*;
import tableTennisInstructor.model.drools.facts.training.*;
import java.util.ArrayList;
import java.util.List;


rule "Create event BadBodyPosition if there are 2 successive bad positions"
    when
    	$tre: TrainingExecution()
    	$badBodyPos1 :SkillExecutionEvent(
    						trainingExecutionId == $tre.id,
    						rightBodyMovement == false,
    						badBodyPositionProcessed == false
    					)
    	$badBodyPos2 :SkillExecutionEvent(
            						trainingExecutionId == $tre.id,
            						rightBodyMovement == false,
            						badBodyPositionProcessed == false,
            						$badBodyPos1 after [1s, 3s] this
            					)

    then
        $badBodyPos1.setBadBodyPositionProcessed(true);
        $badBodyPos2.setBadBodyPositionProcessed(true);
    	update($badBodyPos1);
    	update($badBodyPos2);
    	insert(new BadBodyPositionEvent($tre.id));
    	System.out.println("Previse uzastopnih LOSIH POZICIJA TELA");
end

