//created on: May 5, 2020
package cepTrainingMonitor

//list any import classes here.
import tableTennisInstructor.model.drools.events.*;
import tableTennisInstructor.model.drools.facts.training.*;
import java.util.ArrayList;
import java.util.List;
import java.lang.Long;


rule "Create RacketAngleCorrectionEvent with correction message when 2 or more badRacketAngles with same angle occurs"
	salience 100
    when
    	// uzmes tek kreirani event i pogledas 6 sek u proslos da li ima jos koji istog ugla
    	//
    	$e1: BadRacketAngleEvent(processed == false, $angle: angle)
        $e2: BadRacketAngleEvent(
                                 id != $e1.id &&
                                 processed == false &&
                                 ((angle > 0  && $angle > 0)|| (angle < 0  && $angle < 0 )) &&
                                 this after[0s, 3s] $e1
        					    )
    then
        $e1.setProcessed(true);
        $e2.setProcessed(true);
    	update($e1);
    	update($e2);
        RacketAngleCorrectionEvent raketCorrectionEvent = new RacketAngleCorrectionEvent($e1.trainingExecutionId);
       	raketCorrectionEvent.setMessage($e1.angle > 0 ? "Zatrovi reket" : "Otvori reket");
		insert(raketCorrectionEvent);
        System.out.println("Kreiran event za KOREKCIJU UGLA reketa");

end

rule "Create RacketAngleCorrectionEvent without correction message when 2 or more badRacketAngles with different angle occurs"
	salience 90
    when
        $e1: BadRacketAngleEvent(processed == false, $angle: angle)
        $e2: BadRacketAngleEvent(
                  id != $e1.id &&
                  processed == false &&
                  ((angle > 0  && $angle < 0)|| (angle < 0  && $angle > 0 )) &&
                  this after [0s, 3s] $e1
                )
    then
        $e1.setProcessed(true);
        $e2.setProcessed(true);
        update($e1);
        update($e2);
        RacketAngleCorrectionEvent raketCorrectionEvent = new RacketAngleCorrectionEvent($e1.trainingExecutionId);
       	raketCorrectionEvent.setMessage("Nepravilan ugao reketa ali promenljiv");
		insert(raketCorrectionEvent);
        System.out.println("Kreiran event za KOREKCIJU UGLA reketa bez poruke");
end
