//created on: May 5, 2020
package cepTrainingMonitor

//list any import classes here.
import tableTennisInstructor.model.drools.events.*;
import tableTennisInstructor.model.drools.facts.training.*;
import java.util.ArrayList;
import java.lang.Long;

import accumulate tableTennisInstructor.util.accumulateFunctions.TooMuchMissFunction tooMuchMissAcc;


query isMoreThen(double missBound)
	$total: Number(doubleValue >= missBound) from accumulate(
       				$e:SkillExecutionEvent(),
					tooMuchMissAcc($e)
       		) 
end 


rule "Create TuMuchMissEvent when BEGINER training is done and there are more then 40% of miss"
	salience 100
    when
       	$endTr: EndTrainingEvent(processed == false)
       	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.BEGINNER)
       	isMoreThen(0.4;)
    then
    	System.out.println("previse promasaja za pocetnicki nivo");
    	modify ($endTr) {setProcessed(true);}
    	insert(new ToMuchMiss());
    	insert(new CreateMarkEvent());
end

rule "Create TuMuchMissEvent when INTERMEDIATE training is done and there are more then 35% of miss"
    salience 100
    when
       	$endTr: EndTrainingEvent(processed == false)
       	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.INTERMEDIATE)
		isMoreThen(0.35;)
    then
    	modify ($endTr) {setProcessed(true);}
    	insert(new ToMuchMiss());
    	insert(new CreateMarkEvent());
end


rule "Create TuMuchMissEvent when ADVANCED training is done and there are more then 25% of miss"
    salience 100
    when
       	$endTr: EndTrainingEvent(processed == false)
       	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.ADVANCED)
		isMoreThen(0.25;)
    then
    	modify ($endTr) {setProcessed(true);}
    	insert(new ToMuchMiss());
    	insert(new CreateMarkEvent());
end

rule "Create CreateMarkEvent when training is done and there are not critical number of misses"
    salience 90
    when
       	$endTr: EndTrainingEvent(processed == false)
       	
    then
    	modify ($endTr) {setProcessed(true);}
    	insert(new CreateMarkEvent());
    	System.out.println("NEMA PREVISE PROMASAJA");
end
