//created on: May 5, 2020
package cepTrainingMonitor

//list any import classes here.
import tableTennisInstructor.model.drools.events.*;
import tableTennisInstructor.model.drools.facts.training.*;
import java.util.ArrayList;
import java.lang.Long;


//declare any global variables here


rule "Create badRacketSpeedEvent when training lvl iz BEGINER and racketSpeed is wrong "
    when
    	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.BEGINNER)
    	$lastShot: SkillExecutionEvent(trainingExecutionId == $tre.id,
        									(deltaSpeed >= 5.0 || deltaSpeed <= -5.0 ) &&
        									badRacketSpeedProcessed == false
        							   )
    then
        $lastShot.setBadRacketSpeedProcessed(true);
        BadRacketSpeedEvent badRaketEvent = new BadRacketSpeedEvent($tre.id);
       	badRaketEvent.setSpeed($lastShot.deltaSpeed);
        update($lastShot);
        insert(badRaketEvent);
        System.out.println("Kreiran event losa brzina reketa za pocetnicki nivo");

end

rule "Create badRacketSpeedEvent when training lvl iz INTERMEDIATE and racketSpeed is wrong "

    when
    	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.INTERMEDIATE)
    	$lastShot: SkillExecutionEvent(trainingExecutionId == $tre.id,
        									(deltaSpeed >= 4.0 || deltaSpeed <= -4.0 ) &&
        									badRacketSpeedProcessed == false
        									)
    then
            $lastShot.setBadRacketSpeedProcessed(true);
            BadRacketSpeedEvent badRaketEvent = new BadRacketSpeedEvent($tre.id);
           	badRaketEvent.setSpeed($lastShot.deltaSpeed);
            update($lastShot);
            insert(badRaketEvent);
            System.out.println("Kreiran event losa brzina reketa za ITNERMEDIATE nivo");
end

rule "Create badRacketSpeedEvent when training lvl iz ADVANCED and racketSpeed is wrong "

    when
    	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.ADVANCED)
    	$lastShot: SkillExecutionEvent(trainingExecutionId == $tre.id,
        									(deltaSpeed >= 3.0 || deltaSpeed <= -3.0 ) &&
        									badRacketSpeedProcessed == false
        									)
    then
        $lastShot.setBadRacketSpeedProcessed(true);
        BadRacketSpeedEvent badRaketEvent = new BadRacketSpeedEvent($tre.id);
        badRaketEvent.setSpeed($lastShot.deltaSpeed);
        update($lastShot);
        insert(badRaketEvent);
        System.out.println("Kreiran event losa brzina reketa za Advanced nivo");
end
