//created on: May 5, 2020
package cepTrainingMonitor

//list any import classes here.
import tableTennisInstructor.model.drools.events.*;
import tableTennisInstructor.model.drools.facts.training.*;
import java.util.ArrayList;
import java.lang.Long;


//declare any global variables here


rule "Create badRacketAngleEvent when training lvl is BEGINER and deltaAngle is >=15 or <= -15"

    when
    	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.BEGINNER)
    	$lastShot: SkillExecutionEvent(
                   						trainingExecutionId == $tre.id,
                           				(deltaAngle >= 15.0 || deltaAngle <= -15.0 ) &&
                           				badRacketAngleProcessed == false
                   						)

    then
        $lastShot.setBadRacketAngleProcessed(true);
        BadRacketAngleEvent badRaketEvent = new BadRacketAngleEvent($tre.id);
        badRaketEvent.setAngle($lastShot.deltaAngle);
        update($lastShot);
        insert(badRaketEvent);
        System.out.println("Kreiran event los ugao reketa za pocetnicki nivo");

end

rule "Create badRacketAngleEvent when training lvl iz INTERMEDIATE and deltaAngle is >=10 or <= -10 "

    when
    	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.INTERMEDIATE)
    	$lastShot: SkillExecutionEvent(trainingExecutionId == $tre.id,
        								(deltaAngle >= 10.0 || deltaAngle <= -10.0 ) &&
        								badRacketAngleProcessed == false
        						      )
    then
         $lastShot.setBadRacketAngleProcessed(true);
         BadRacketAngleEvent badRaketEvent = new BadRacketAngleEvent($tre.id);
         badRaketEvent.setAngle($lastShot.deltaAngle);
         update($lastShot);
         insert(badRaketEvent);
         System.out.println("Kreiran event los ugao reketa za INTERMEDIATE nivo");

end


rule "Create badRacketAngleEvent when training lvl iz ADVANCED and deltaAngle is >=5 or <= -5 "

    when
    	$tre: TrainingExecution(training.trainingLevel == TrainingLevel.ADVANCED)
    	$lastShot: SkillExecutionEvent(trainingExecutionId == $tre.id,
        									(deltaAngle >= 5.0 || deltaAngle <= -5.0 ) &&
        									badRacketAngleProcessed == false
        									)
    then
         modify($lastShot){setBadRacketAngleProcessed(true)}
         BadRacketAngleEvent badRaketEvent = new BadRacketAngleEvent($tre.id);
         badRaketEvent.setAngle($lastShot.deltaAngle);
         insert(badRaketEvent);
         System.out.println("Kreiran event los ugao reketa za ADVANCED nivo");
end


