//created on: May 2, 2020
package trainingPlan

import tableTennisInstructor.model.drools.facts.*;
import tableTennisInstructor.model.drools.facts.training.*;

import static tableTennisInstructor.util.SalienceFunctions.*;

rule "Set LONG training duration and create TrainingChooseFact"
    salience($trReq.trainingDuration >= 4 ? 1: 0)
	when
        $trReq: TrainingChooseRequestFact($userId: userId)
        not TrainingChooseFact(userId == $userId)
    then
    	System.out.println("LONG trening");
    	TrainingChooseFact tfc = new TrainingChooseFact();
    	tfc.setUserId($userId);
    	tfc.setTrainingDuradtion(TrainingDuration.LONG);
    	insert(tfc);
end

rule "Set MEDIUM training duration and create TrainingChooseFact"
	salience( ($trReq.trainingDuration < 4 && $trReq.trainingDuration >= 3)  ? 1: 0)
    when
        $trReq: TrainingChooseRequestFact($userId: userId)
        not TrainingChooseFact(userId == $userId)
    then
    	System.out.println("MEDIUM duration trening");
    	TrainingChooseFact tfc = new TrainingChooseFact();
    	tfc.setUserId($userId);
    	tfc.setTrainingDuradtion(TrainingDuration.MEDIUM);
    	insert(tfc);
end

rule "Set SHORT training duration and create TrainingChooseFact"
	salience($trReq.trainingDuration < 3 ? 1: 0)
    when
        $trReq: TrainingChooseRequestFact($userId: userId)
        not TrainingChooseFact(userId == $userId)
    then
    	System.out.println("SHORT duration trening");
    	TrainingChooseFact tfc = new TrainingChooseFact();
    	tfc.setUserId($userId);
    	tfc.setTrainingDuradtion(TrainingDuration.SHORT);
    	insert(tfc);
end