//created on: May 2, 2020
package trainingPlan

import tableTennisInstructor.model.drools.facts.*;
import tableTennisInstructor.model.drools.facts.training.*;
//declare any global variables here

rule "Good Healht condition"
	no-loop 
	salience 100
    when
    	$trReq: TrainingChooseRequestFact($userId: userId, $userHealth: userHealth)
    	$tfc: TrainingChooseFact(userId == $userId) @Watch (userId)
    	UserHealth( heartbeat <= 70, systolic < 135, systolic > 105, diastolic < 90, diastolic > 70) from $userHealth
    then
    	System.out.println("good zdravlje");
    	$tfc.setUserHealthState(UserHealthState.GOOD);
        update( $tfc );
end

rule "Bad Healht condition"
	no-loop 
	salience 100
    when
    	$trReq: TrainingChooseRequestFact($userId: userId, $userHealth: userHealth)
    	$tfc: TrainingChooseFact(userId == $userId) @Watch (userId)
    	UserHealth(
		    	 	 heartbeat > 80
		        	 ||	 (systolic < 100 || systolic > 140)
		        	 ||  (diastolic < 65 || diastolic > 95) 
    	 			)
    		 from $userHealth
    then
    	$tfc.setUserHealthState(UserHealthState.BAD);
        update( $tfc );
end


rule "Average Health Condition"
	salience 90
    when
    	$trReq: TrainingChooseRequestFact($userId: userId, $userHealth: userHealth)
    	$tfc: TrainingChooseFact(userId == $userId, userHealthState == UserHealthState.UNKNOWN) @Watch (userId)
    then
    	$tfc.setUserHealthState(UserHealthState.AVERAGE);
        update( $tfc );
end
