//created on: May 2, 2020
package integracija

import tableTennisInstructor.model.drools.facts.*;
import tableTennisInstructor.model.drools.facts.training.*;

rule "Set LONG training duration and create TrainingChooseFact"
    when
        $trReq: TrainingChooseRequestFact($userId: userId, trainingDuration >= 4)
        not TrainingChooseFact(userId == $userId)
    then
    	System.out.println("LONG trening");
    	TrainingChooseFact tfc = new TrainingChooseFact();
    	tfc.setUserId($userId);
    	tfc.setTrainingDuradtion(TrainingDuration.LONG);
    	insert(tfc);
end

rule "Set MEDIUM training duration and create TrainingChooseFact"
    when
        $trReq: TrainingChooseRequestFact($userId: userId, trainingDuration >= 3, trainingDuration < 4 )
        not TrainingChooseFact(userId == $userId)
    then
    	System.out.println("MEDIUM trening");
    	TrainingChooseFact tfc = new TrainingChooseFact();
    	tfc.setUserId($userId);
    	tfc.setTrainingDuradtion(TrainingDuration.MEDIUM);
    	insert(tfc);
end

rule "Set SHORT training duration and create TrainingChooseFact"
    when
        $trReq: TrainingChooseRequestFact($userId: userId, trainingDuration < 3)
        not TrainingChooseFact(userId == $userId)
    then
    	System.out.println("kratak trening");
    	TrainingChooseFact tfc = new TrainingChooseFact();
    	tfc.setUserId($userId);
    	tfc.setTrainingDuradtion(TrainingDuration.SHORT);
    	insert(tfc);
end